// <auto-generated />
using System;
using DreamCine.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DreamCine.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260701104355_SeedInitialData")]
    partial class SeedInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DreamCine.Core.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("DreamCine.Core.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Science Fiction"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Drama"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Comedy"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Thriller"
                        });
                });

            modelBuilder.Entity("DreamCine.Core.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<decimal?>("Rating")
                        .HasPrecision(3, 1)
                        .HasColumnType("decimal(3,1)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ReleaseDate");

                    b.HasIndex("StatusId");

                    b.HasIndex("Title");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Paul Atreides unites with Chani...",
                            Duration = 166,
                            Rating = 8.8m,
                            ReleaseDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            StatusId = 1,
                            Title = "Dune: Part Two"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Arthur Fleck is institutionalized...",
                            Duration = 138,
                            Rating = 7.5m,
                            ReleaseDate = new DateTime(2024, 10, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            StatusId = 2,
                            Title = "Joker: Folie à Deux"
                        },
                        new
                        {
                            Id = 3,
                            Description = "The irresponsible hero Deadpool...",
                            Duration = 127,
                            Rating = 8.1m,
                            ReleaseDate = new DateTime(2024, 7, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            StatusId = 1,
                            Title = "Deadpool & Wolverine"
                        });
                });

            modelBuilder.Entity("DreamCine.Core.Models.MovieGenre", b =>
                {
                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.HasKey("MovieId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("MovieGenres");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            GenreId = 1
                        },
                        new
                        {
                            MovieId = 1,
                            GenreId = 2
                        },
                        new
                        {
                            MovieId = 2,
                            GenreId = 3
                        },
                        new
                        {
                            MovieId = 2,
                            GenreId = 5
                        },
                        new
                        {
                            MovieId = 3,
                            GenreId = 1
                        },
                        new
                        {
                            MovieId = 3,
                            GenreId = 4
                        });
                });

            modelBuilder.Entity("DreamCine.Core.Models.MovieSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ScreenId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SessionTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("ScreenId");

                    b.ToTable("MovieSessions");
                });

            modelBuilder.Entity("DreamCine.Core.Models.Screen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("ScreenNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Screens");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 30,
                            ScreenNumber = 1
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 20,
                            ScreenNumber = 2
                        });
                });

            modelBuilder.Entity("DreamCine.Core.Models.Seat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ScreenId")
                        .HasColumnType("int");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ScreenId");

                    b.ToTable("Seats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ScreenId = 1,
                            SeatNumber = "A1"
                        },
                        new
                        {
                            Id = 2,
                            ScreenId = 1,
                            SeatNumber = "A2"
                        },
                        new
                        {
                            Id = 3,
                            ScreenId = 1,
                            SeatNumber = "A3"
                        },
                        new
                        {
                            Id = 4,
                            ScreenId = 1,
                            SeatNumber = "A4"
                        },
                        new
                        {
                            Id = 5,
                            ScreenId = 1,
                            SeatNumber = "A5"
                        },
                        new
                        {
                            Id = 6,
                            ScreenId = 1,
                            SeatNumber = "A6"
                        },
                        new
                        {
                            Id = 7,
                            ScreenId = 1,
                            SeatNumber = "A7"
                        },
                        new
                        {
                            Id = 8,
                            ScreenId = 1,
                            SeatNumber = "A8"
                        },
                        new
                        {
                            Id = 9,
                            ScreenId = 1,
                            SeatNumber = "A9"
                        },
                        new
                        {
                            Id = 10,
                            ScreenId = 1,
                            SeatNumber = "A10"
                        },
                        new
                        {
                            Id = 11,
                            ScreenId = 1,
                            SeatNumber = "B1"
                        },
                        new
                        {
                            Id = 12,
                            ScreenId = 1,
                            SeatNumber = "B2"
                        },
                        new
                        {
                            Id = 13,
                            ScreenId = 1,
                            SeatNumber = "B3"
                        },
                        new
                        {
                            Id = 14,
                            ScreenId = 1,
                            SeatNumber = "B4"
                        },
                        new
                        {
                            Id = 15,
                            ScreenId = 1,
                            SeatNumber = "B5"
                        },
                        new
                        {
                            Id = 16,
                            ScreenId = 1,
                            SeatNumber = "B6"
                        },
                        new
                        {
                            Id = 17,
                            ScreenId = 1,
                            SeatNumber = "B7"
                        },
                        new
                        {
                            Id = 18,
                            ScreenId = 1,
                            SeatNumber = "B8"
                        },
                        new
                        {
                            Id = 19,
                            ScreenId = 1,
                            SeatNumber = "B9"
                        },
                        new
                        {
                            Id = 20,
                            ScreenId = 1,
                            SeatNumber = "B10"
                        },
                        new
                        {
                            Id = 21,
                            ScreenId = 1,
                            SeatNumber = "C1"
                        },
                        new
                        {
                            Id = 22,
                            ScreenId = 1,
                            SeatNumber = "C2"
                        },
                        new
                        {
                            Id = 23,
                            ScreenId = 1,
                            SeatNumber = "C3"
                        },
                        new
                        {
                            Id = 24,
                            ScreenId = 1,
                            SeatNumber = "C4"
                        },
                        new
                        {
                            Id = 25,
                            ScreenId = 1,
                            SeatNumber = "C5"
                        },
                        new
                        {
                            Id = 26,
                            ScreenId = 1,
                            SeatNumber = "C6"
                        },
                        new
                        {
                            Id = 27,
                            ScreenId = 1,
                            SeatNumber = "C7"
                        },
                        new
                        {
                            Id = 28,
                            ScreenId = 1,
                            SeatNumber = "C8"
                        },
                        new
                        {
                            Id = 29,
                            ScreenId = 1,
                            SeatNumber = "C9"
                        },
                        new
                        {
                            Id = 30,
                            ScreenId = 1,
                            SeatNumber = "C10"
                        },
                        new
                        {
                            Id = 31,
                            ScreenId = 2,
                            SeatNumber = "A1"
                        },
                        new
                        {
                            Id = 32,
                            ScreenId = 2,
                            SeatNumber = "A2"
                        },
                        new
                        {
                            Id = 33,
                            ScreenId = 2,
                            SeatNumber = "A3"
                        },
                        new
                        {
                            Id = 34,
                            ScreenId = 2,
                            SeatNumber = "A4"
                        },
                        new
                        {
                            Id = 35,
                            ScreenId = 2,
                            SeatNumber = "A5"
                        },
                        new
                        {
                            Id = 36,
                            ScreenId = 2,
                            SeatNumber = "A6"
                        },
                        new
                        {
                            Id = 37,
                            ScreenId = 2,
                            SeatNumber = "A7"
                        },
                        new
                        {
                            Id = 38,
                            ScreenId = 2,
                            SeatNumber = "A8"
                        },
                        new
                        {
                            Id = 39,
                            ScreenId = 2,
                            SeatNumber = "A9"
                        },
                        new
                        {
                            Id = 40,
                            ScreenId = 2,
                            SeatNumber = "A10"
                        },
                        new
                        {
                            Id = 41,
                            ScreenId = 2,
                            SeatNumber = "B1"
                        },
                        new
                        {
                            Id = 42,
                            ScreenId = 2,
                            SeatNumber = "B2"
                        },
                        new
                        {
                            Id = 43,
                            ScreenId = 2,
                            SeatNumber = "B3"
                        },
                        new
                        {
                            Id = 44,
                            ScreenId = 2,
                            SeatNumber = "B4"
                        },
                        new
                        {
                            Id = 45,
                            ScreenId = 2,
                            SeatNumber = "B5"
                        },
                        new
                        {
                            Id = 46,
                            ScreenId = 2,
                            SeatNumber = "B6"
                        },
                        new
                        {
                            Id = 47,
                            ScreenId = 2,
                            SeatNumber = "B7"
                        },
                        new
                        {
                            Id = 48,
                            ScreenId = 2,
                            SeatNumber = "B8"
                        },
                        new
                        {
                            Id = 49,
                            ScreenId = 2,
                            SeatNumber = "B9"
                        },
                        new
                        {
                            Id = 50,
                            ScreenId = 2,
                            SeatNumber = "B10"
                        });
                });

            modelBuilder.Entity("DreamCine.Core.Models.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Now Showing"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Coming Soon"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ended"
                        });
                });

            modelBuilder.Entity("DreamCine.Core.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookingTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("MovieSessionId")
                        .HasColumnType("int");

                    b.Property<decimal>("PurchasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SeatId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("MovieSessionId");

                    b.HasIndex("SeatId");

                    b.HasIndex("UserId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "297de5bf-b618-40c6-b2f3-e36a56d1971e",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "3dfcb2e7-0d2a-476a-873d-694b87f5f238",
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = "9c2cc2e8-ae82-4245-8774-edf5f34d6833",
                            Name = "Staff",
                            NormalizedName = "STAFF"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DreamCine.Core.Models.Movie", b =>
                {
                    b.HasOne("DreamCine.Core.Models.Status", "Status")
                        .WithMany("Movies")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Status");
                });

            modelBuilder.Entity("DreamCine.Core.Models.MovieGenre", b =>
                {
                    b.HasOne("DreamCine.Core.Models.Genre", "Genre")
                        .WithMany("MovieGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DreamCine.Core.Models.Movie", "Movie")
                        .WithMany("MovieGenres")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("DreamCine.Core.Models.MovieSession", b =>
                {
                    b.HasOne("DreamCine.Core.Models.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DreamCine.Core.Models.Screen", "Screen")
                        .WithMany()
                        .HasForeignKey("ScreenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("Screen");
                });

            modelBuilder.Entity("DreamCine.Core.Models.Seat", b =>
                {
                    b.HasOne("DreamCine.Core.Models.Screen", "Screen")
                        .WithMany()
                        .HasForeignKey("ScreenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Screen");
                });

            modelBuilder.Entity("DreamCine.Core.Models.Ticket", b =>
                {
                    b.HasOne("DreamCine.Core.Models.MovieSession", "MovieSession")
                        .WithMany()
                        .HasForeignKey("MovieSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DreamCine.Core.Models.Seat", "Seat")
                        .WithMany()
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DreamCine.Core.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MovieSession");

                    b.Navigation("Seat");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DreamCine.Core.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DreamCine.Core.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DreamCine.Core.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DreamCine.Core.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DreamCine.Core.Models.Genre", b =>
                {
                    b.Navigation("MovieGenres");
                });

            modelBuilder.Entity("DreamCine.Core.Models.Movie", b =>
                {
                    b.Navigation("MovieGenres");
                });

            modelBuilder.Entity("DreamCine.Core.Models.Status", b =>
                {
                    b.Navigation("Movies");
                });
#pragma warning restore 612, 618
        }
    }
}
